Fixed two unusual "unused value" warnings.
io/dfeval.c: In function 'interp_linear_flagged':
io/dfeval.c:1027:26: error: left-hand operand of comma expression has no effect [-Werror=unused-value]
  for (i = 0; i < ncorners, i != j; ++i)
                          ^
io/dfeval.c:1035:28: error: left-hand operand of comma expression has no effect [-Werror=unused-value]
    for (i = 0; i < ncorners, i != j; ++i)

The problem is that the "i < ncorners" is evaluated and discarded.
The result of the expression is the rightmost clause ("i != j").
In both cases, "i" can never be greater than "ncorners" via
transitivity, so it's ok to delete that clause.  The error did
not have an effect on program correctness.